### ISSUE TITLE
provide better error msg when the port is not exposed

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/conu#70]
```
Traceback (most recent call last):
  File "docs/source/examples/webserver.py", line 41, in <module>
    test_webserver()
  File "docs/source/examples/webserver.py", line 36, in test_webserver
    http_response = container.http_request(path="/")
  File "/home/tt/.local/lib/python3.6/site-packages/conu/apidefs/container.py", line 45, in http_request
    port = port or self.get_ports()[0]
IndexError: list index out of range
```

**Comment by dhodovsk** [comment]
Are these steps to reproduce?
```python
from conu import DockerImage, DockerRunBuilder
image = DockerImage('fedora', tag='26')
command = DockerRunBuilder(command=["sleep", "500"])
container = image.run_via_binary(command)
container.get_ports()
```

If so, this can be closed.

**Comment by TomasTomecek** [comment]
Yup, that's exactly the reproducer.
